# Generated by Django 6.0.3 on 2026-03-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogg_body',
            new_name='blog_body',
        ),
    ]
